apiVersion: apps/v1
kind: Deployment
metadata:
  name: trend-web
  namespace: trend
labels:
  app: trend-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trend-web
  template:
    metadata:
      labels:
        app: trend-web
    spec:
      containers:
        - name: trend-web
          image: DOCKERHUB_USER/project-trend
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
